# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'DPAppDoctor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DPAppDoctor
  pod 'FBRetainCycleDetector'

  target 'DPAppDoctorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DPAppDoctorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
